//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AIRLINE
    {
        public int AIRLINEID { get; set; }
        public string AIRLINENAME { get; set; }
        public string AIRLINECODE { get; set; }
    }
}
