//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSearch.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Flight_DataEntities : DbContext
    {
        public Flight_DataEntities()
            : base("name=Flight_DataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AIRLINE> AIRLINEs { get; set; }
        public virtual DbSet<FLIGHT> FLIGHTS { get; set; }
        public virtual DbSet<LOCATION> LOCATIONs { get; set; }
    }
}
