//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightSearch.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LOCATION
    {
        public int LOCATIONID { get; set; }
        public string LOCATIONNAME { get; set; }
        public string LOCATIONCODE { get; set; }
    }
}
